force-app/main/default/objects/Account/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <label>Experience</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Github__c.field-meta.xml
<CustomField>
    <fullName>Github__c</fullName>
    <label>Github</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Account/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <label>Image Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <label>Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agentforce</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Certificates__c.field-meta.xml
<CustomField>
    <fullName>Total_Certificates__c</fullName>
    <label>Total Certificates</label>
    <summaryForeignKey>Certificate__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Total_Projects__c.field-meta.xml
<CustomField>
    <fullName>Total_Projects__c</fullName>
    <label>Total Projects</label>
    <summaryForeignKey>Project__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trailhead__c.field-meta.xml
<CustomField>
    <fullName>Trailhead__c</fullName>
    <label>Trailhead</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Certificate__c/Certificate__c.object-meta.xml
<CustomObject>
    <label>Certificate</label>
    <nameField>
        <label>Certificate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce Platform</fullName>
            </value>
            <value>
                <fullName>Data Cloud</fullName>
            </value>
            <value>
                <fullName>Agentforce</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Image_Name__c.field-meta.xml
<CustomField>
    <fullName>Image_Name__c</fullName>
    <label>Image Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Certificate__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>Udemy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Github__c.field-meta.xml
<CustomField>
    <fullName>Github__c</fullName>
    <label>Github</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/youtube__c.field-meta.xml
<CustomField>
    <fullName>youtube__c</fullName>
    <label>youtube</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Project_Page__mdt/Project_Page__mdt.object-meta.xml
<CustomObject>
    <label>Project Page</label>
    <pluralLabel>Project Pages</pluralLabel>
</CustomObject>

force-app/main/default/objects/Project_Page__mdt/fields/isSkill__c.field-meta.xml
<CustomField>
    <fullName>isSkill__c</fullName>
    <defaultValue>true</defaultValue>
    <label>isSkill</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project_Page__mdt/fields/value__c.field-meta.xml
<CustomField>
    <fullName>value__c</fullName>
    <label>value</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Project_Skill__c/Project_Skill__c.object-meta.xml
<CustomObject>
    <label>Project Skill</label>
    <nameField>
        <displayFormat>ProSkill-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Skill__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Skills</relationshipLabel>
    <relationshipName>Project_Skills</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Skill__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Project Skills</relationshipLabel>
    <relationshipName>Project_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Percentage__c.field-meta.xml
<CustomField>
    <fullName>Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Percentage</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomMetaddataUtil.cls
/**
 * @description       : 
 * @author            : Venkatesh M
 * @group             : 
 * @last modified on  : 03-31-2026
 * @last modified by  : Venkatesh M
**/
public with sharing class CustomMetaddataUtil {

    @AuraEnabled(cacheable=true)
    public static List<Project_Page__mdt> getAllSkillsAndTechnologies(){
        return [SELECT id,Label,value__c ,isSkill__c FROM Project_Page__mdt ORDER BY label];
    }

    @AuraEnabled(cacheable=true)
    public static Account getMyAccountDetails(){
        return [SELECT Id,Name,Bio__c,Image_Name__c,Total_Certificates__c, Total_Projects__c,Skills__c,Type, Email__c,
        LinkedIn__c, Trailhead__c, Designation__c, Description,Github__c, Phone, PhotoUrl,Experience__c,BillingCountry
        FROM Account 
        WHERE Type = 'Portfolio' AND Name ='Venkat M' LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static List<Skill__c> getAllSkillsWithPercentages(){
        return [SELECT id,Name,percentage__c FROM Skill__c ORDER BY percentage__c DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Certificate__c> getAllCertificates(){
        return [SELECT id,Name,Category__c, Image_Name__c, Issued_Date__c, Source__c FROM Certificate__c ORDER BY Issued_Date__c DESC];
    }

    @AuraEnabled(cacheable=true)
    public static List<Project__c> getAllProjects(){
        return [SELECT id,Name,Description__c, Difficulty__c, Github__c, Website__c, youtube__c,Created_Date__c ,(SELECT Id,Skill__r.Name FROM Project_Skills__r ) FROM Project__c ];
    }
}